name = "IriyaReloaded"
author = "Iriya"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c150ed618cea8990ca95b53c43b94c16273dfbebbd7573777b8e06dc5cb38188"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
