name = "IriyaReloaded"
author = "Iriya"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf263cb4af2aa969ef773bec288fde34ec9b7a95220fac9563e7a4e3b179dc5"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
