name = "IriyaReloaded"
author = "Iriya"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9415a573d23162ee483107aead06d95d0f016390d89d8b8c4a17dc223005b2d"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
