name = "IriyaReloaded"
author = "Iriya"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eeba4f4be812da0113f8986e9c85a15336ab09bb8ef6cac8060a1f0c5e7a7a4"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
