name = "IriyaReloaded"
author = "Iriya"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50445866c7dace23df762e16b72f37b32a7bceb25b01c17f6562dc7baecf8618"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
