name = "IriyaReloaded"
author = "Iriya"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3596081d1636587a5b3b190394e1c38a8376b7edec1bea42594b90ea5d0070ae"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
